Feature/push 18136 kotlin to java
Pushwoosh/pushwoosh-flutter pull request #4
Opened 2019-03-05 05:25 UTC by nikolleto

2019-03-07 10:25 UTC, AAEvstefeev requested changes

2019-03-07 10:25 UTC, AAEvstefeev commented on Source/pushwoosh/android/src/main/java/com/pushwoosh/plugin/PushwooshNotificationServiceExtension.java
> +            if (ai.metaData != null) {
ApplicationInfo неплохобы на null проверить

2019-03-07 10:25 UTC, AAEvstefeev commented on Source/pushwoosh/android/src/main/java/com/pushwoosh/plugin/PushwooshPlugin.java
> +        result.error(e.getClass().getSimpleName(), message, Log.e(e.getClass().getName(), e.getMessage(), e));
ну короче что то пошло не так, Log.e печатает стек трейс, а не возвращает его.

2019-03-07 10:25 UTC, AAEvstefeev commented on Source/pushwoosh/android/src/main/java/com/pushwoosh/plugin/PushwooshPlugin.java
> +        if (appId != null)
можно скобочки добавить

2019-03-15 04:59 UTC, nikolleto commented
замечания исправлены

2019-04-03 08:14 UTC, merged